version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: bulk_orch_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3310:3306"   # host:container
    volumes:
      - bulk_orch_db_data:/var/lib/mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]

  bulk_orch_app:
    image: sanah22/bulk-orchestration:latest
    container_name: bulk_orch_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      USER_MANAGEMENT_BASE_URL: ${USER_MANAGEMENT_BASE_URL}
    ports:
      - "8083:8083"

volumes:
  bulk_orch_db_data:
